### ISSUE TITLE
Incorrect calculation of pixel resolution

### ISSUE THREAD

**Issue by WeatherGod** [Global-Water-Security-Center/data-exploration#1]
https://github.com/Global-Water-Security-Center/data-exploration/blob/7407c118762f285b991716e52868591e0fffbeed/netcdf_to_geotiff.py#L63

This is incorrect for two reasons:
1. It suffers from the fencepost problem.
2. I have seen situations where data gets produced such that the first and last longitudes end up the same, or overlapping, or even have the discontinuity in the middle of the grid! Such a dataset would produce the wrong result even if you correct for the fencepost problem.

I propose a nifty solution that has served me well over the years:
```
np.median(np.diff(coord_array))
```

It isn't perfect by any stretch, and there might be better approaches, but it has worked decently for me. Another thing to consider is using `rioxarray` to load up the netcdf and try to autodetect the spatial array, but my success with its autodetection of underspec'ed datasets is mixed.

**Comment by richpsharp** [comment]
neat! thanks for the tip!
